### ISSUE TITLE
10/31 レビュー依頼1

### ISSUE THREAD

**Issue by donutsmogmog** [donutsmogmog/Graduation_work_saran_app#24]
## 各種情報
サービスの概要とMVPで検証する事柄：

K-POPアイドルのファンに特化したスケジュール管理ツールです。
アーティストやイベント（ライブ、CDリリース、音楽番組出演など）をスケジュール登録の際、選択式とし、一般的なスケジュールアプリにない利便性を向上させました。

MVPリリースでは、会員登録、スケジュールの登録、またカレンダー表示から更新・削除について検証をお願いいたします。

サービス名：**Saran!**
サービスURL：https://graduation-work-saran-app.onrender.com

## READMEレビュー時にMVPリリース時点で実装予定だった機能

- [ ] ~~K-POP推し活紹介ページ（簡単な用語説明、音楽番組ランキングへの投票ガイド）~~ →次項目参照
- [x] 会員登録
- [x] ログイン
- [x] イベント登録/詳細/編集/削除
- [ ] ~~イベント検索~~ →次項目参照
- [x] スケジュールのカレンダー表示（Simple Carender使用）

## READMEレビュー時から変更した機能
 - [x] スケジュールのカレンダー表示（Simple Carender使用）
 →スケジュールアプリらしさを表現する必要があると考え、カレンダー形式でのスケジュール表示機能を追加しました。
- [x] サービス概要の説明
 →トップページにユーザーへの利用を促進するための説明が必要と考え追加しました。

- [x] ~~K-POP推し活紹介ページ（簡単な用語説明、音楽番組ランキングへの投票ガイド）~~
→MVP時点では不要と考え、本リリース後に変更しました。
- [x] ~~イベント検索~~
→MVP時点では不要と考え、本リリース後に変更しました。

## サービスイメージがわかるようなスクリーンショット等
[![Image from Gyazo](https://i.gyazo.com/b0ffcf93961e8f9e89ceaf0238f51d38.png)](https://gyazo.com/b0ffcf93961e8f9e89ceaf0238f51d38)

**Comment by Tsuchiya2** [comment]
機能確認が取れました。LGTMです。
引き続き本リリースに向けて開発頑張ってください。

以下、LGTMを出した方々に共通してお伝えしている内容になります。
（Webアプリを就職活動で活用される方向けの内容になります）

===== 本リリースまでに以下の項目を実装してください =====
□ 独自ドメイン反映
    -> DNSやSSLの対応も必要になるのでアピールになり、URLを書類等に記載するときの見栄えも良くなります。
□ OGP（静的 or 動的）
    -> SNS等でシェアするときの見栄えが良くなります。Webアプリであればどんなアプリでも取り入れられるので対応しておきましょう。
□ RSpec（モデルテスト+システムテスト or モデルテスト+リクエストテスト）
    -> 開発における品質の意識や開発効率の意識の高さをアピールできます。Request Specをメインに最低限各機能に正常にアクセスできるか程度はテストで確認できるようにしておきましょう。
□ CI（GitHubActions）
    -> 実際に開発現場でも使われており、アプリ外で技術のアピールが出来るものです。RSpecと合わせて実装を行いましょう。
□ Rubocopを使ってのリファクタリング
    -> Lintチェックツールは開発現場で広く使われています。コードのLintを整えておくことはチームで開発することを意識するうえでとても大切になるので取り入れておきましょう。

他のプログラミング学習者のWebアプリと異なることをアピールするために、よりインパクトのある機能を複数盛り込むことが重要になってきます。
□ SNSログイン（Google or LINE）
    -> ほとんどのアプリに取り入れられてユーザー体験の向上や技術のアピールにつながるので取り入れましょう。
□ 検索機能のアップデート（オートコンプリート、マルチ検索等）   ※検索機能がある場合
    -> 特にオートコンプリートは検索体験の向上だけではなくJS系の技術も取り入れていることをアピール出来るので積極的に取り入れましょう。

ユーザー体験という面では以下の項目も大切です。
□ オートログイン
    -> ユーザー登録後に再度ログイン操作を行わせないことでユーザー体験を向上させられます。
□ 使い方説明がある
    -> 初めて訪れたユーザーに呈して使い方の説明があることで体験を向上させられます。
□ レスポンシブ対応
    -> いずれのデバイスでも綺麗にサービスが活用できることで体験が良くなります。
□ 利用規約・プライバシーポリシーを未ログイン状態でも確認できる
    -> 利用規約・プライバシーポリシーがあることで、ちゃんとしたサービスという印象を与えられます。
□ ローディングアニメーション（処理が重い箇所）
    -> 処理が重い箇所に何の対応も無いとユーザーが正しく操作できたのか困惑してしまいます。そうした際はローディングアニメーションを表示させることで体験が向上します。

**Comment by donutsmogmog** [comment]
ありがとうございます。本リリースに向けて上記を含め実装してまいります。
